### ISSUE TITLE
Documentation: Desktop view assumed

### ISSUE THREAD

**Issue by ShalokShalom** [ResiliaDev/Planga#7]
Which image? :D 

![test](https://funkyimg.com/i/2UE7w.png)

**Comment by Qqwy** [comment]
Thank you for making an issue! We'll fix it ASAP :slightly_smiling_face: .

**Comment by ShalokShalom** [comment]
Sure :)

**Comment by Qqwy** [comment]
Done!

- The picture is positioned more clearly, coming before the accompanying text.
- The reference to the picture no longer contains the text 'to the right', and is an in-page hyperlink to the picture.
